image: node:12-alpine
pipelines:
  branches:
    main:
      - step:
          name: Start Deployment to Production
          script:
            - echo "Start Deployment"
      - step:
          name: Deploy to prod
          trigger: manual
          caches:
            - node
          script:
            - pipe: atlassian/serverless-deploy:0.2.2
              variables: 
                LAMBDA_OUT: $LAMBDA_OUT_PRD
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_KEY
                EXTRA_ARGS: '--stage prod'
    development:
      - step:
          name: Deploy to hml
          caches:
            - node
          script:
            - pipe: atlassian/serverless-deploy:0.2.2
              variables: 
                LAMBDA_OUT: $LAMBDA_OUT_HML
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_KEY
                EXTRA_ARGS: '--stage hml'