image: node:11.13.0-alpine

pipelines:
  custom: # Pipelines that are triggered manually
    deployment-to-prod:
      - step:
          name: Deploy to prod
          caches:
            - node
          script:
            - echo "Deploy to prod"
  branches:
    development:
      - step:
          name: Deploy to homolog
          caches:
            - node
          script:
            - npm install -g serverless
            - serverless config credentials --stage homolog --provider aws --key ${AWS_ACCESS_KEY} --secret ${AWS_SECRET_KEY}
            - serverless deploy --stage homolog
