service: RekoReko-free

provider:
  name: aws
  runtime: python2.7
  stage: staging
  region: us-east-1
  memorySize: 128

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:GetObject
        - s3:DeleteObject
      Resource: arn:aws:s3:::com.rekoreko.free
    - Effect: Allow
      Action:
        - rekognition:DetectLabels
      Resource: "*"

package:
  exclude:
    - .gitignore
    - bitbucket-pipelines.yml
    - serverless.yml
  excludeDevDependencies: true
  individually: true

functions:
  lambda_handler:
    handler: handler.lambda_handler
    events:
      - s3:
          bucket: com.rekoreko.free
          event: s3:ObjectCreated:*
    destinations:
      onSuccess: ${LAMBDA_OUT}
